### PR TITLE
Revert "postgres-types feature implementation"

### PR DESCRIPTION
**Pull request by novacrazy**
Reverts rkyv/rkyv#532

While I doubt rust-postgres/postgres-types will [accept my PR](https://github.com/sfackler/rust-postgres/pull/1178) anytime soon, I realized forking individual crates and adding support to them in-crate is subpar compared to just forking rust-postgres/postgres-types itself, as shortly after my first PR I started getting confusing cyclic dependency errors due to patching so many individual crates, notably with `smol_str` which rkyv also brings in if enabled. It feels kind of wrong to include this feature in the massive 0.8 release when it may be superseded later. 

I sincerely apologize for the inconsistency/indecisiveness of this.

### CODE REVIEW

**Comment by novacrazy** [comment]
Test failures are all unrelated, just bad timing as you're refactoring things.

**Comment by djkoloski** [comment]
> Test failures are all unrelated, just bad timing as you're refactoring things.

Yep, I'll retrigger the CI as soon as the latest commit lands.

> I sincerely apologize for the inconsistency/indecisiveness of this.

No need to be sorry! 🙂

**Comment by djkoloski** [comment]
Ah, looks like I don't have push rights on this branch of your fork. Could you rebase on main and force-push? In case you don't have an upstream remote yet:

```
git remote add upstream https://github.com/rkyv/rkyv
git fetch upstream
git rebase upstream/main
git push --force
```

**Comment by djkoloski** [comment]
Thank you!

**Pull request merged**
