### PR TITLE
Default to `pointer_width_32` if pointer width is unspecified

### LINKED ISSUE #460: size_[16,32,64] features and library development
I am developing a data structures library, and I want to have optional support for rkyv.
So, I added rkyv to my Cargo.toml:
```toml
[dependencies.rkyv]
version = "0.7"
optional = true
default-features = false
```
My library is `no_std`, so I've disabled the default features.

However, `cargo build --all-features` no longer works, failing with:
> error: one of ["size_16", "size_32", or "size_64"] features must be enabled

Because these features are all mutually exclusive (exactly one must be enabled), my library should not be enabling any of them, to allow downstream consumers to choose the repr that they want.
However, that means that I can't build my code unless I pick one of these features.

I've tried also adding rkyv to my `[dev-dependencies]`, which does make `cargo build --all-features --all-targets` work (because `--all-targets` builds unit tests which pulls in dev deps).
However, I still can't do anything else (like build documentation etc) without adding `--features rkyv/size_32` to all of my commands, which is not ideal.
The best I've been able to do is add `__rkyv_hack = ["rkyv/size_32"]` to my crate `[features]`, which works, but is quite hacky.

Is there a better way to do this? Did I miss something in the documentation?

---

While this use case could probably benefit from [Pre-RFC: Mutually-excusive, global features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618), such a concept doesn't currently exist :sob:

### PR DESCRIPTION
**Pull request by Sky9x**
WIP

Fixes #460

### CODE REVIEW

**Comment by Sky9x** [comment]
maybe a better approach would be to check if none of them are set in a build script then manually set feature=pointer_width_32

**Comment by Sky9x** [comment]
or what if we remove the pointer_width_32 feature entirely (just have 16 & 64 for overriding the default)

**Comment by djkoloski** [comment]
We should still have a way for end users to explicitly declare "this must be 32-bit" so that they don't accidentally get overridden.

**Comment by Sky9x** [comment]
> We should still have a way for end users to explicitly declare "this must be 32-bit" so that they don't accidentally get overridden.

yes yes you're right

**Comment by Sky9x** [comment]
that works, thanks

**Comment by Alxandr** [comment]
Any chance this can be back-ported to stable (and released)?

**Pull request merged**
