### PR TITLE
Fix typo in Docs::deserialize.md

### PR DESCRIPTION
**Pull request by canewsin**

### CODE REVIEW

**Review by djkoloski — COMMENTED** [review]
This one's not misspelled, "sped up" is the past tense of "speed up".

**Comment by canewsin** [comment]
lack of commas in docs at certain places, makes terms some what confusing.

**Comment by djkoloski** [comment]
I did notice that there appears to be a duplicate "a" in there after "more or less". That sentence could be reworded better though. How about "This provides traditional deserialization, being sped up somewhat by having a very compatible representation."

**Comment by canewsin** [comment]
somewhat and compatible wording is redundant in a single sentence.

**Comment by canewsin** [comment]
https://github.com/rkyv/rkyv/blob/62f0bef9fd3e4c4e762ee574f7dafe05cdfb1320/book_src/zero-copy-deserialization.md?plain=1#L86-L88

These lines also needs rework, especially this 
> it doesn't *scale* with our data

**Comment by canewsin** [comment]
> it doesn't _scale_ with our data

For this 
> This operation is almost zero work, and more importantly data size doesn't increase any work, it's always just a pointer offset and a cast to access our data.

**Comment by djkoloski** [comment]
I think these suggestions could improve the documentation, and I'd be happy to review a PR with them as changes. Since this PR is obsolete, I'm going to close it for now.

**Pull request closed without merging**
