### PR TITLE
Implement PartialOrd between Option/ArchivedOption.

### PR DESCRIPTION
**Pull request by gz**
This implements PartialOrd for comparing Option<T> and ArchivedOption<T>.

### CODE REVIEW

**Comment by djkoloski** [comment]
See #434, there are some issues with adding `PartialOrd` impls and `PartialEq` impls. I think it's more of a Rust problem personally, but the ergonomic impact is unfortunately real.

**Comment by gz** [comment]
Do you want me to put this behind a feature flag as discussed on discord? Any preference for the name of the feature?

**Comment by djkoloski** [comment]
I think a feature flag would be good. Maybe something like `extra_traits`, that mirrors what `syn` does.

**Comment by gz** [comment]
I added the feature flag, but currently seems I can't test the code due to an (unrelated?) errors:

```
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
    Updating git repository `https://github.com/rkyv/rend`
error: failed to select a version for the requirement `rend = "^0.5"`
candidate versions found which didn't match: 0.5.0-pre5
location searched: Git repository https://github.com/rkyv/rend?branch=master
required by package `rkyv v0.8.0 (/home/gz/workspace/rkyv/rkyv)`
if you are looking for the prerelease package it needs to be specified explicitly
    rend = { version = "0.5.0-pre5" }
```

**Comment by djkoloski** [comment]
Sorry about that, the `master` branch is stuck between 0.7 and 0.8 right now. As part of the 0.8 update I'll be cleaning up the branch structure here. I'm going to merge this commit and pick it into the `0.8` branch as well. Do you need this in a 0.7 release?

**Comment by gz** [comment]
>Do you need this in a 0.7 release?
Not super urgent, if you plan to release 0.8 anyways soon I can wait.

**Pull request merged**
